version: "2.1"
services:
  database:
    image: mysql:8.0.33
    container_name: mysqldb
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'userpassword'
      MYSQL_DATABASE: 'testdb'
